# Generated by Django 3.2.9 on 2021-12-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payment_date', models.TimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('wedding_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.wedding')),
            ],
        ),
    ]
