# Generated by Django 3.2.9 on 2021-12-06 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_event_productincluded_providesproduct_providesservice_serviceincluded_status'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inevent',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inevent',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.event'),
        ),
        migrations.AddField(
            model_name='inevent',
            name='participate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.participate'),
        ),
        migrations.AddField(
            model_name='participate',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.person'),
        ),
        migrations.AddField(
            model_name='participate',
            name='wedding_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weddings.wedding'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
